"""Initial schema - entities, funding_events, contracts, signals

Revision ID: 1beac9820b60
Revises: 
Create Date: 2026-02-02 16:05:05.433911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1beac9820b60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('name_variants', sqlite.JSON(), nullable=True),
    sa.Column('entity_type', sa.Enum('STARTUP', 'PRIME', 'INVESTOR', 'AGENCY', name='entitytype'), nullable=False),
    sa.Column('cage_code', sa.String(length=10), nullable=True),
    sa.Column('duns_number', sa.String(length=13), nullable=True),
    sa.Column('ein', sa.String(length=10), nullable=True),
    sa.Column('headquarters_location', sa.Text(), nullable=True),
    sa.Column('founded_date', sa.Date(), nullable=True),
    sa.Column('technology_tags', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entities_cage_code'), ['cage_code'], unique=False)
        batch_op.create_index('ix_entities_cage_duns', ['cage_code', 'duns_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_canonical_name'), ['canonical_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_duns_number'), ['duns_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_entities_entity_type'), ['entity_type'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('contract_number', sa.Text(), nullable=False),
    sa.Column('contracting_agency', sa.Text(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('award_date', sa.Date(), nullable=True),
    sa.Column('period_of_performance_start', sa.Date(), nullable=True),
    sa.Column('period_of_performance_end', sa.Date(), nullable=True),
    sa.Column('naics_code', sa.String(length=10), nullable=True),
    sa.Column('psc_code', sa.String(length=10), nullable=True),
    sa.Column('place_of_performance', sa.Text(), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_number')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_award_date'), ['award_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_contracting_agency'), ['contracting_agency'], unique=False)
        batch_op.create_index('ix_contracts_entity_agency', ['entity_id', 'contracting_agency'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_naics_code'), ['naics_code'], unique=False)
        batch_op.create_index('ix_contracts_naics_psc', ['naics_code', 'psc_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_psc_code'), ['psc_code'], unique=False)

    op.create_table('funding_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.Enum('VC_ROUND', 'SBIR_PHASE_1', 'SBIR_PHASE_2', 'SBIR_PHASE_3', 'CONTRACT', 'ACQUISITION', name='fundingeventtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('investors_awarders', sqlite.JSON(), nullable=True),
    sa.Column('round_stage', sa.String(length=50), nullable=True),
    sa.Column('raw_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('funding_events', schema=None) as batch_op:
        batch_op.create_index('ix_funding_entity_date', ['entity_id', 'event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_events_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_funding_events_event_type'), ['event_type'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('signal_type', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('detected_date', sa.Date(), nullable=True),
    sa.Column('evidence', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'VALIDATED', 'FALSE_POSITIVE', name='signalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_detected_date'), ['detected_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index('ix_signals_entity_type', ['entity_id', 'signal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_signal_type'), ['signal_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_status'), ['status'], unique=False)
        batch_op.create_index('ix_signals_status_date', ['status', 'detected_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index('ix_signals_status_date')
        batch_op.drop_index(batch_op.f('ix_signals_status'))
        batch_op.drop_index(batch_op.f('ix_signals_signal_type'))
        batch_op.drop_index('ix_signals_entity_type')
        batch_op.drop_index(batch_op.f('ix_signals_entity_id'))
        batch_op.drop_index(batch_op.f('ix_signals_detected_date'))

    op.drop_table('signals')
    with op.batch_alter_table('funding_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funding_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_funding_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_funding_events_entity_id'))
        batch_op.drop_index('ix_funding_entity_date')

    op.drop_table('funding_events')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_psc_code'))
        batch_op.drop_index('ix_contracts_naics_psc')
        batch_op.drop_index(batch_op.f('ix_contracts_naics_code'))
        batch_op.drop_index(batch_op.f('ix_contracts_entity_id'))
        batch_op.drop_index('ix_contracts_entity_agency')
        batch_op.drop_index(batch_op.f('ix_contracts_contracting_agency'))
        batch_op.drop_index(batch_op.f('ix_contracts_award_date'))

    op.drop_table('contracts')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entities_entity_type'))
        batch_op.drop_index(batch_op.f('ix_entities_duns_number'))
        batch_op.drop_index(batch_op.f('ix_entities_canonical_name'))
        batch_op.drop_index('ix_entities_cage_duns')
        batch_op.drop_index(batch_op.f('ix_entities_cage_code'))

    op.drop_table('entities')
    # ### end Alembic commands ###
