"""Add entity merge tracking - merged_into_id and entity_merges table

Revision ID: a42a7c8b39d4
Revises: 1beac9820b60
Create Date: 2026-02-02 16:23:59.031605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a42a7c8b39d4'
down_revision: Union[str, Sequence[str], None] = '1beac9820b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_merges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_entity_id', sa.String(length=36), nullable=False),
    sa.Column('target_entity_id', sa.String(length=36), nullable=False),
    sa.Column('merge_reason', sa.Enum('IDENTIFIER_MATCH', 'NAME_SIMILARITY', 'NAME_AND_LOCATION', 'NAME_AND_NAICS', 'MANUAL', name='mergereason'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('source_name', sa.Text(), nullable=False),
    sa.Column('target_name', sa.Text(), nullable=False),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_merges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_merges_source_entity_id'), ['source_entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_merges_target_entity_id'), ['target_entity_id'], unique=False)

    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merged_into_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_entities_merged_into_id'), ['merged_into_id'], unique=False)
        batch_op.create_foreign_key('fk_entities_merged_into', 'entities', ['merged_into_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_entities_merged_into', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_entities_merged_into_id'))
        batch_op.drop_column('merged_into_id')

    with op.batch_alter_table('entity_merges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_merges_target_entity_id'))
        batch_op.drop_index(batch_op.f('ix_entity_merges_source_entity_id'))

    op.drop_table('entity_merges')
    # ### end Alembic commands ###
