"""Add defensibility layer tables

Revision ID: eb5aadea1862
Revises: a42a7c8b39d4
Create Date: 2026-02-26 11:02:11.141210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'eb5aadea1862'
down_revision: Union[str, Sequence[str], None] = 'a42a7c8b39d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraper_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_fetched', sa.Numeric(precision=8, scale=0), nullable=True),
    sa.Column('records_new', sa.Numeric(precision=8, scale=0), nullable=True),
    sa.Column('records_updated', sa.Numeric(precision=8, scale=0), nullable=True),
    sa.Column('entities_created', sa.Numeric(precision=8, scale=0), nullable=True),
    sa.Column('entities_matched', sa.Numeric(precision=8, scale=0), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checkpoint', sqlite.JSON(), nullable=True),
    sa.Column('config', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scraper_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scraper_runs_source_name'), ['source_name'], unique=False)
        batch_op.create_index('ix_scraper_runs_source_started', ['source_name', 'started_at'], unique=False)

    op.create_table('entity_corrections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('correction_type', sa.String(length=50), nullable=False),
    sa.Column('entity_a_id', sa.String(length=36), nullable=False),
    sa.Column('entity_b_id', sa.String(length=36), nullable=True),
    sa.Column('source_name_a', sa.Text(), nullable=True),
    sa.Column('source_name_b', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('confidence_before', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('confidence_after', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=50), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('correction_source', sa.String(length=100), nullable=True),
    sa.Column('evidence', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['entity_a_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['entity_b_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_corrections_correction_type'), ['correction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_corrections_entity_a_id'), ['entity_a_id'], unique=False)

    op.create_table('entity_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('core_business', sa.String(length=50), nullable=True),
    sa.Column('composite_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('freshness_adjusted_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('policy_tailwind_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('sbir_count', sa.Numeric(precision=6, scale=0), nullable=True),
    sa.Column('sbir_total_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('contract_count', sa.Numeric(precision=6, scale=0), nullable=True),
    sa.Column('contract_total_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('regd_count', sa.Numeric(precision=6, scale=0), nullable=True),
    sa.Column('regd_total_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('active_signals', sqlite.JSON(), nullable=True),
    sa.Column('lifecycle_stage', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'snapshot_date', name='uq_entity_snapshot_date')
    )
    with op.batch_alter_table('entity_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_snapshots_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_snapshots_snapshot_date'), ['snapshot_date'], unique=False)
        batch_op.create_index('ix_snapshots_entity_date', ['entity_id', 'snapshot_date'], unique=False)

    op.create_table('report_deliveries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('report_slug', sa.Text(), nullable=False),
    sa.Column('recipient', sa.String(length=100), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=False),
    sa.Column('snapshot', sqlite.JSON(), nullable=True),
    sa.Column('feedback_rating', sa.String(length=50), nullable=True),
    sa.Column('feedback_notes', sa.Text(), nullable=True),
    sa.Column('feedback_date', sa.DateTime(), nullable=True),
    sa.Column('outcome_confirmed', sa.Boolean(), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_deliveries', schema=None) as batch_op:
        batch_op.create_index('ix_deliveries_entity_date', ['entity_id', 'delivered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_deliveries_entity_id'), ['entity_id'], unique=False)

    op.create_table('signal_validations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('signal_id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('signal_type', sa.Text(), nullable=False),
    sa.Column('validation_type', sa.String(length=50), nullable=False),
    sa.Column('validation_source', sa.String(length=100), nullable=True),
    sa.Column('expected_outcome', sa.Text(), nullable=True),
    sa.Column('actual_outcome', sa.Text(), nullable=True),
    sa.Column('lead_time_months', sa.Numeric(precision=4, scale=0), nullable=True),
    sa.Column('evidence', sqlite.JSON(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_validations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_validations_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signal_validations_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index('ix_validations_signal_type', ['signal_type', 'validation_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal_validations', schema=None) as batch_op:
        batch_op.drop_index('ix_validations_signal_type')
        batch_op.drop_index(batch_op.f('ix_signal_validations_signal_id'))
        batch_op.drop_index(batch_op.f('ix_signal_validations_entity_id'))

    op.drop_table('signal_validations')
    with op.batch_alter_table('report_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_deliveries_entity_id'))
        batch_op.drop_index('ix_deliveries_entity_date')

    op.drop_table('report_deliveries')
    with op.batch_alter_table('entity_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshots_entity_date')
        batch_op.drop_index(batch_op.f('ix_entity_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_entity_snapshots_entity_id'))

    op.drop_table('entity_snapshots')
    with op.batch_alter_table('entity_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_corrections_entity_a_id'))
        batch_op.drop_index(batch_op.f('ix_entity_corrections_correction_type'))

    op.drop_table('entity_corrections')
    with op.batch_alter_table('scraper_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_scraper_runs_source_started')
        batch_op.drop_index(batch_op.f('ix_scraper_runs_source_name'))

    op.drop_table('scraper_runs')
    # ### end Alembic commands ###
