#!/usr/bin/env python3
"""
Generate polished PDF prospect report from Defense Alpha database.

Reads the same data as generate_prospect_report.py but renders to PDF
with professional formatting, executive summary, and branded footer.

Usage:
    python scripts/generate_pdf_report.py
"""

import struct
import sys
from collections import defaultdict
from datetime import date
from decimal import Decimal
from pathlib import Path

import numpy as np
from fpdf import FPDF

sys.path.insert(0, str(Path(__file__).parent.parent))

from sqlalchemy import func
from processing.database import SessionLocal
from processing.models import (
    Entity, EntityType, FundingEvent, FundingEventType,
    Contract, Signal, SignalStatus, SbirEmbedding,
)
from processing.signal_detector import (
    SIGNAL_SBIR_TO_CONTRACT, SIGNAL_RAPID_GROWTH, SIGNAL_SBIR_TO_VC,
    SIGNAL_OUTSIZED_AWARD, SIGNAL_SBIR_PHASE_2, SIGNAL_SBIR_PHASE_3,
    SIGNAL_MULTI_AGENCY, SIGNAL_HIGH_PRIORITY_TECH, SIGNAL_FIRST_DOD_CONTRACT,
    SIGNAL_SBIR_STALLED, SIGNAL_CUSTOMER_CONCENTRATION,
    SIGNAL_SBIR_GRADUATION_SPEED, SIGNAL_TIME_TO_CONTRACT, SIGNAL_FUNDING_VELOCITY,
)

EMBEDDING_DIM = 384
REPORT_DATE = date.today().strftime("%B %d, %Y")
FOOTER_TEXT = (
    f"Generated by Defense Alpha  |  Proprietary  |  "
    f"Data sources: USASpending, SBIR.gov, SEC EDGAR  |  {REPORT_DATE}"
)

POSITIVE_WEIGHTS = {
    SIGNAL_SBIR_TO_CONTRACT: 3.0, SIGNAL_RAPID_GROWTH: 2.5,
    SIGNAL_SBIR_TO_VC: 2.0, SIGNAL_OUTSIZED_AWARD: 2.0,
    SIGNAL_SBIR_PHASE_2: 1.5, SIGNAL_SBIR_PHASE_3: 2.0,
    SIGNAL_MULTI_AGENCY: 1.5, SIGNAL_HIGH_PRIORITY_TECH: 1.0,
    SIGNAL_FIRST_DOD_CONTRACT: 1.0, SIGNAL_SBIR_GRADUATION_SPEED: 1.5,
    SIGNAL_TIME_TO_CONTRACT: 2.0, SIGNAL_FUNDING_VELOCITY: 1.5,
}
NEGATIVE_WEIGHTS = {
    SIGNAL_SBIR_STALLED: -2.0, SIGNAL_CUSTOMER_CONCENTRATION: -1.5,
}
ALL_WEIGHTS = {**POSITIVE_WEIGHTS, **NEGATIVE_WEIGHTS}

SIGNAL_DISPLAY = {
    SIGNAL_SBIR_TO_CONTRACT: "SBIR->Contract",
    SIGNAL_RAPID_GROWTH: "Rapid Growth",
    SIGNAL_SBIR_TO_VC: "SBIR + VC Raise",
    SIGNAL_OUTSIZED_AWARD: "Outsized Award",
    SIGNAL_SBIR_PHASE_2: "SBIR Phase II",
    SIGNAL_SBIR_PHASE_3: "SBIR Phase III",
    SIGNAL_MULTI_AGENCY: "Multi-Agency",
    SIGNAL_HIGH_PRIORITY_TECH: "High-Priority Tech",
    SIGNAL_FIRST_DOD_CONTRACT: "First DoD Contract",
    SIGNAL_SBIR_GRADUATION_SPEED: "Fast SBIR Graduation",
    SIGNAL_TIME_TO_CONTRACT: "Fast Time-to-Contract",
    SIGNAL_FUNDING_VELOCITY: "Funding Velocity",
    SIGNAL_SBIR_STALLED: "SBIR Stalled",
    SIGNAL_CUSTOMER_CONCENTRATION: "Customer Concentration",
}

EXCLUDE_NAMES = {
    "anduril", "l3harris", "l3 harris", "rtx", "raytheon", "northrop grumman",
    "lockheed martin", "boeing", "general dynamics", "bae systems", "leidos",
    "saic", "booz allen", "palantir", "general atomics", "textron",
}

QUERIES = [
    "RF antenna radio tactical communications mesh networking spectrum",
    "SIGINT signals intelligence spectrum sensing electronic warfare EW",
    "satellite communications ground station SATCOM terminal",
    "software defined radio waveform tactical data link",
]

TOP5_RATIONALES = {
    0: "Highest RF relevance among signal-rich companies; mesh radio SBIR with Phase II graduation and VC backing.",
    1: "Strongest composite score in cohort; 3D RF spectrum visualization with 5 positive signals and $16.9M raised.",
    2: "Top technology relevance (0.693); proliferated GEO SATCOM with $358M in private capital at growth stage.",
    3: "Radar disruption systems with fastest SBIR-to-contract transition (279 days) and $8.9M contract win.",
    4: "Seven SBIR awards across C2 and protection platforms; $12.3M VC raise with fast Phase II graduation.",
}


# ── Data helpers (same logic as generate_prospect_report.py) ────────────────

def deserialize_embedding(data):
    n = len(data) // 4
    return np.array(struct.unpack(f"{n}f", data), dtype=np.float32)


def semantic_search(db, model, query, top_n=300):
    query_vec = model.encode([query])[0]
    query_vec = query_vec / np.linalg.norm(query_vec)
    rows = db.query(SbirEmbedding).all()
    embs = np.zeros((len(rows), EMBEDDING_DIM), dtype=np.float32)
    meta = []
    for i, r in enumerate(rows):
        embs[i] = deserialize_embedding(r.embedding)
        meta.append({"entity_id": r.entity_id, "award_title": r.award_title})
    norms = np.linalg.norm(embs, axis=1, keepdims=True)
    norms[norms == 0] = 1
    embs /= norms
    sims = embs @ query_vec
    ent_scores, ent_titles = {}, defaultdict(list)
    for i, m in enumerate(meta):
        eid, s = m["entity_id"], float(sims[i])
        ent_titles[eid].append((s, m["award_title"]))
        if eid not in ent_scores or s > ent_scores[eid]:
            ent_scores[eid] = s
    ranked = sorted(ent_scores.items(), key=lambda x: -x[1])[:top_n]
    return {e: s for e, s in ranked}, ent_titles


def compute_composite(db, eid):
    signals = db.query(Signal).filter(
        Signal.entity_id == eid, Signal.status == SignalStatus.ACTIVE).all()
    pos, neg, pos_list, neg_list = 0.0, 0.0, [], []
    for sig in signals:
        w = ALL_WEIGHTS.get(sig.signal_type, 0.0)
        c = float(sig.confidence_score or 0)
        wt = w * c
        entry = {"name": SIGNAL_DISPLAY.get(sig.signal_type, sig.signal_type),
                 "score": round(wt, 2)}
        if w > 0:
            pos += wt; pos_list.append(entry)
        elif w < 0:
            neg += wt; neg_list.append(entry)
    pos_list.sort(key=lambda x: -x["score"])
    return {"composite": round(pos + neg, 2), "positive": round(pos, 2),
            "negative": round(neg, 2), "pos_signals": pos_list, "neg_signals": neg_list}


def get_activity(db, eid):
    sbir_types = [FundingEventType.SBIR_PHASE_1, FundingEventType.SBIR_PHASE_2,
                  FundingEventType.SBIR_PHASE_3]
    latest_sbir = db.query(func.max(FundingEvent.event_date)).filter(
        FundingEvent.entity_id == eid, FundingEvent.event_type.in_(sbir_types)).scalar()
    total_sbir = float(db.query(func.sum(FundingEvent.amount)).filter(
        FundingEvent.entity_id == eid, FundingEvent.event_type.in_(sbir_types)).scalar() or 0)
    sbir_count = db.query(func.count(FundingEvent.id)).filter(
        FundingEvent.entity_id == eid, FundingEvent.event_type.in_(sbir_types)).scalar() or 0
    latest_contract = db.query(func.max(Contract.award_date)).filter(
        Contract.entity_id == eid).scalar()
    total_contract = float(db.query(func.sum(Contract.contract_value)).filter(
        Contract.entity_id == eid).scalar() or 0)
    contract_count = db.query(func.count(Contract.id)).filter(
        Contract.entity_id == eid).scalar() or 0
    latest_regd = db.query(func.max(FundingEvent.event_date)).filter(
        FundingEvent.entity_id == eid,
        FundingEvent.event_type == FundingEventType.REG_D_FILING).scalar()
    total_regd = float(db.query(func.sum(FundingEvent.amount)).filter(
        FundingEvent.entity_id == eid,
        FundingEvent.event_type == FundingEventType.REG_D_FILING).scalar() or 0)
    dates = [d for d in [latest_sbir, latest_contract, latest_regd] if d]
    latest = max(dates) if dates else None
    total = total_sbir + total_contract + total_regd
    if total > 100_000_000: stage = "Growth / Scale-up"
    elif total > 20_000_000: stage = "Series B+"
    elif total > 5_000_000: stage = "Series A"
    elif total > 1_000_000: stage = "Seed / Early"
    else: stage = "Pre-seed / SBIR"
    return {"latest_sbir": latest_sbir, "latest_contract": latest_contract,
            "latest_regd": latest_regd, "latest": latest, "total_sbir": total_sbir,
            "total_contract": total_contract, "total_regd": total_regd,
            "sbir_count": sbir_count, "contract_count": contract_count, "stage": stage}


def fmt_currency(v):
    if v >= 1e9: return f"${v/1e9:.1f}B"
    if v >= 1e6: return f"${v/1e6:.1f}M"
    if v >= 1e3: return f"${v/1e3:.0f}K"
    return f"${v:.0f}"


def build_prospects(db, model):
    merged_sim, all_titles = {}, defaultdict(list)
    for q in QUERIES:
        scores, titles = semantic_search(db, model, q)
        for eid, s in scores.items():
            if eid not in merged_sim or s > merged_sim[eid]:
                merged_sim[eid] = s
            all_titles[eid].extend(titles.get(eid, []))
    prospects = []
    for eid, sim in merged_sim.items():
        if sim < 0.35:
            continue
        e = db.query(Entity).filter(Entity.id == eid).first()
        if not e or e.merged_into_id or e.entity_type != EntityType.STARTUP:
            continue
        if any(x in e.canonical_name.lower() for x in EXCLUDE_NAMES):
            continue
        sc = compute_composite(db, eid)
        if sc["composite"] <= 0 or not sc["pos_signals"]:
            continue
        act = get_activity(db, eid)
        seen, titles = set(), []
        for s, t in sorted(all_titles.get(eid, []), key=lambda x: -x[0]):
            if t not in seen:
                seen.add(t); titles.append(t)
        rank = 0.55 * sim + 0.45 * min(sc["composite"] / 6.0, 1.0)
        prospects.append({"name": e.canonical_name, "loc": e.headquarters_location or "",
                          "sim": sim, **sc, "activity": act, "titles": titles,
                          "rank": rank})
    prospects.sort(key=lambda x: -x["rank"])
    return prospects[:20]


# ── PDF class ───────────────────────────────────────────────────────────────

def safe_text(text):
    """Sanitize text for latin-1 compatible PDF fonts."""
    try:
        text.encode("latin-1")
        return text
    except UnicodeEncodeError:
        return text.encode("latin-1", errors="replace").decode("latin-1")


class ReportPDF(FPDF):

    def header(self):
        if self.page_no() == 1:
            return  # title page has its own header
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, "Defense Alpha  |  RF & Communications Emerging Company Report",
                  align="L", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(0, 51, 102)
        self.set_line_width(0.4)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, FOOTER_TEXT, align="C")

    # ── helpers ──

    def section_title(self, text):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(0, 51, 102)
        self.cell(0, 10, text, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(0, 51, 102)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def subsection_title(self, text):
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(0, 51, 102)
        self.cell(0, 8, text, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def body_text(self, text):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(40, 40, 40)
        self.multi_cell(0, 4.5, safe_text(text))
        self.ln(1)

    def label_value(self, label, value, bold_value=False):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(60, 60, 60)
        lw = self.get_string_width(label + "  ")
        self.cell(lw, 4.5, label + "  ")
        self.set_font("Helvetica", "B" if bold_value else "", 9)
        self.set_text_color(40, 40, 40)
        self.cell(0, 4.5, safe_text(str(value)), new_x="LMARGIN", new_y="NEXT")

    def bullet(self, text, indent=12):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(40, 40, 40)
        self.set_x(self.l_margin + indent)
        self.multi_cell(0, 4.5, safe_text("- " + text))

    def signal_bullet(self, text, positive=True):
        self.set_font("Helvetica", "", 9)
        if positive:
            marker = "[+] "
            self.set_text_color(0, 120, 60)
        else:
            marker = "[-] "
            self.set_text_color(180, 60, 30)
        self.set_x(self.l_margin + 12)
        self.multi_cell(0, 4.5, safe_text(marker + text))
        self.set_text_color(40, 40, 40)

    def check_page_break(self, height=50):
        if self.get_y() + height > 270:
            self.add_page()


# ── Build PDF ───────────────────────────────────────────────────────────────

def build_pdf(prospects, output_path):
    pdf = ReportPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(15, 15, 15)

    # ── PAGE 1: Title page ──────────────────────────────────────────────────
    pdf.add_page()

    pdf.ln(30)
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 14, "Defense Alpha", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 10, "RF & Communications", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 10, "Emerging Company Report", align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)
    pdf.set_draw_color(0, 51, 102)
    pdf.set_line_width(0.5)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.ln(8)

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 7, REPORT_DATE, align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, "20 Prospects  |  Proprietary & Confidential",
             align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(15)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(80, 80, 80)
    lines = [
        "Data Sources:",
        "5,147 DoD contracts from USASpending.gov (2020-2025)",
        "1,653 SBIR awards with semantic embeddings",
        "1,979 SEC Form D filings",
        "Proprietary composite scoring across 13 signal types",
    ]
    for i, ln in enumerate(lines):
        if i == 0:
            pdf.set_font("Helvetica", "B", 9)
        else:
            pdf.set_font("Helvetica", "", 9)
            ln = "-  " + ln
        pdf.cell(0, 5, ln, align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 5, "This report was generated from Defense Alpha's database, not general AI knowledge.",
             align="C", new_x="LMARGIN", new_y="NEXT")

    # ── PAGE 2: Executive Summary ───────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Executive Summary")

    pdf.body_text(
        "This report identifies the 20 most promising emerging companies in the "
        "RF, communications, and electronic warfare sector of the U.S. defense industrial base. "
        "Companies were surfaced through semantic search over 1,653 SBIR award titles, then "
        "filtered and ranked using Defense Alpha's proprietary composite scoring system, which "
        "weighs 13 intelligence signal types including SBIR phase progression, contract wins, "
        "private capital raises, multi-agency interest, and risk indicators."
    )
    pdf.ln(2)
    pdf.body_text(
        "The ranking blends technology relevance (55%) with composite signal strength (45%), "
        "ensuring prospects are both on-topic for RF/communications and backed by strong "
        "momentum indicators. Only startups with at least one positive signal and a net-positive "
        "composite score are included. Major defense primes are excluded."
    )
    pdf.ln(3)

    pdf.subsection_title("Top 5 Recommended Prospects")
    pdf.ln(1)

    for i, p in enumerate(prospects[:5]):
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(0, 51, 102)
        pdf.cell(8, 5.5, f"{i+1}.")
        pdf.cell(0, 5.5, safe_text(p["name"]), new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(60, 60, 60)
        act = p["activity"]
        meta = (f"    {act['stage']}  |  Composite: {p['composite']:.2f}  |  "
                f"Relevance: {p['sim']:.3f}")
        pdf.cell(0, 4.5, safe_text(meta), new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(80, 80, 80)
        rationale = TOP5_RATIONALES.get(i, "")
        pdf.cell(8, 4.5, "")
        pdf.multi_cell(0, 4.5, safe_text(rationale))
        pdf.ln(3)

    # ── PAGE 3+: Ranked Summary Table ───────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Ranked Prospect List")

    # Table header
    col_w = [8, 56, 30, 20, 20, 32, 22]
    headers = ["#", "Company", "Stage", "Score", "Relev.", "Key Signal", "Latest"]

    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(0, 51, 102)
    pdf.set_text_color(255, 255, 255)
    for j, h in enumerate(headers):
        pdf.cell(col_w[j], 6, h, border=1, fill=True, align="C")
    pdf.ln()

    pdf.set_text_color(40, 40, 40)
    for i, p in enumerate(prospects):
        pdf.set_font("Helvetica", "", 7.5)
        if i % 2 == 0:
            pdf.set_fill_color(240, 245, 250)
        else:
            pdf.set_fill_color(255, 255, 255)
        fill = True
        top_sig = p["pos_signals"][0]["name"] if p["pos_signals"] else "-"
        latest = str(p["activity"]["latest"]) if p["activity"]["latest"] else "N/A"
        name = p["name"][:28]

        row = [str(i+1), name, p["activity"]["stage"],
               f"{p['composite']:.2f}", f"{p['sim']:.3f}", top_sig, latest]
        for j, val in enumerate(row):
            align = "C" if j in (0, 3, 4, 6) else "L"
            pdf.cell(col_w[j], 5.5, safe_text(val), border=1, fill=fill, align=align)
        pdf.ln()

    # ── Detailed Profiles ───────────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Detailed Prospect Profiles")

    for i, p in enumerate(prospects):
        pdf.check_page_break(65)

        # Company header
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(0, 51, 102)
        pdf.cell(0, 7, safe_text(f"{i+1}. {p['name']}"), new_x="LMARGIN", new_y="NEXT")

        # Location and stage
        act = p["activity"]
        if p["loc"]:
            pdf.label_value("Location:", p["loc"])
        pdf.label_value("Stage:", act["stage"])
        pdf.label_value("Composite Score:",
                        f"{p['composite']:.2f}  (+{p['positive']:.1f} / {p['negative']:.1f})")
        pdf.label_value("Technology Relevance:", f"{p['sim']:.3f}")
        pdf.ln(2)

        # Technology focus
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(0, 4.5, "Technology Focus:", new_x="LMARGIN", new_y="NEXT")
        for t in p["titles"][:3]:
            pdf.bullet(t[:95])
        pdf.ln(1)

        # Signals
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(0, 4.5, "Intelligence Signals:", new_x="LMARGIN", new_y="NEXT")
        for sig in p["pos_signals"]:
            pdf.signal_bullet(f"{sig['name']} ({sig['score']:+.2f})", positive=True)
        for sig in p["neg_signals"]:
            pdf.signal_bullet(f"{sig['name']} ({sig['score']:+.2f})", positive=False)
        pdf.ln(1)

        # Financials
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(0, 4.5, "Financial Summary:", new_x="LMARGIN", new_y="NEXT")
        if act["sbir_count"]:
            pdf.bullet(f"{act['sbir_count']} SBIR awards ({fmt_currency(act['total_sbir'])})")
        if act["contract_count"]:
            pdf.bullet(f"{act['contract_count']} contracts ({fmt_currency(act['total_contract'])})")
        if act["total_regd"] > 0:
            pdf.bullet(f"Private capital: {fmt_currency(act['total_regd'])}")
        pdf.ln(1)

        # Activity
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(60, 60, 60)
        pdf.cell(0, 4.5, "Recent Activity:", new_x="LMARGIN", new_y="NEXT")
        if act["latest_sbir"]:
            pdf.bullet(f"Latest SBIR: {act['latest_sbir']}")
        if act["latest_contract"]:
            pdf.bullet(f"Latest contract: {act['latest_contract']}")
        if act["latest_regd"]:
            pdf.bullet(f"Latest Reg D filing: {act['latest_regd']}")

        # Divider
        pdf.ln(3)
        pdf.set_draw_color(200, 200, 200)
        pdf.set_line_width(0.2)
        pdf.line(15, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(4)

    # ── Final page: Methodology ─────────────────────────────────────────────
    pdf.add_page()
    pdf.section_title("Methodology")

    pdf.body_text(
        "This report was generated by the Defense Alpha Intelligence Engine using the "
        "following pipeline:"
    )
    pdf.ln(1)

    steps = [
        ("Semantic Search:", "SBIR award titles embedded with all-MiniLM-L6-v2 "
         "sentence-transformer (384-dimensional vectors). Cosine similarity measured "
         "against four technology-specific queries covering RF systems, SIGINT/EW, "
         "SATCOM, and software-defined radio."),
        ("Signal Scoring:", "Composite score computed from 13 signal types including "
         "SBIR progression, contract wins, VC fundraising, multi-agency interest, "
         "and risk indicators (customer concentration, SBIR stalling)."),
        ("Ranking:", "55% technology relevance + 45% composite signal score."),
        ("Filtering:", "Startups only, net-positive composite score, at least one positive "
         "signal, minimum 0.35 semantic similarity, excluding major defense primes."),
    ]
    for label, desc in steps:
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(60, 60, 60)
        lw = pdf.get_string_width(label + " ")
        pdf.cell(lw, 4.5, label + " ")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(40, 40, 40)
        pdf.multi_cell(0, 4.5, desc)
        pdf.ln(2)

    pdf.ln(3)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 5, "Search Queries:", new_x="LMARGIN", new_y="NEXT")
    for q in QUERIES:
        pdf.bullet(f'"{q}"')
    pdf.ln(4)

    pdf.set_draw_color(0, 51, 102)
    pdf.set_line_width(0.3)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 5, "Data Sources:", new_x="LMARGIN", new_y="NEXT")
    sources = [
        "5,147 DoD contracts from USASpending.gov (2020-2025)",
        "1,653 SBIR awards with semantic embeddings",
        "1,979 SEC Form D filings",
        "Proprietary composite scoring across 13 signal types",
    ]
    for s in sources:
        pdf.bullet(s)
    pdf.ln(4)

    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 5,
             "This report was generated from Defense Alpha's database, not general AI knowledge.",
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 8)
    pdf.cell(0, 5, f"Defense Alpha Intelligence Engine v1.0  |  {REPORT_DATE}",
             new_x="LMARGIN", new_y="NEXT")

    # ── Write ───────────────────────────────────────────────────────────────
    pdf.output(str(output_path))
    return pdf.pages_count


def main():
    from sentence_transformers import SentenceTransformer

    db = SessionLocal()
    print("Loading model...")
    model = SentenceTransformer("all-MiniLM-L6-v2")

    print("Building prospects...")
    prospects = build_prospects(db, model)
    print(f"  {len(prospects)} prospects qualified")

    output = Path("reports/rf_comms_prospects.pdf")
    print(f"Generating PDF: {output}")
    pages = build_pdf(prospects, output)
    print(f"Done: {output} ({pages} pages, {output.stat().st_size:,} bytes)")

    db.close()


if __name__ == "__main__":
    main()
